### ISSUE TITLE
a queston in searching the neighbor

### ISSUE THREAD

**Issue by hongshul** [InteractiveComputerGraphics/CompactNSearch#2]
Hi,

I run the splishsplash code and meet a queston in searching the neighbor. 

I go into your funtion **query()** in the file named "CompactNSearcg.cpp". 

In my opinion, you search the piont **va** for its neighbor **vb**s. Is there a mistake in my understanding? If I am right, I wonder that how to get the **va**'s id in the particles(since i use **va.point_id** but it may be larger than the number of the particles) .

Cheers

**Comment by janbender** [comment]
What exactly do you need? An id or the index of the particle?

**Comment by hongshul** [comment]
The index of the particle. 
va's index in the fluid particles

**Comment by hongshul** [comment]
exactly, i need the index of the particle.
i can get the id of va, but i want to transform the id to the index. (Because i want to get its attributes from the fluidmodel. )

**Comment by hongshul** [comment]
@janbender I have soluved my problem. thank you
